config/routes.rb
Rails.application.routes.draw do
  root to: "itineraries#index"

  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/log_out" => "sessions#destroy", as: :log_out

  resources :users
  get '/edittrail' => 'itineraries#edit_trail'
  get '/userphotos' => 'photos#user_index'
  get '/useritineraries' => 'itineraries#user_index'
  get 'signup' => 'users#new'
  
  resources :itineraries do
    resources :photos
  end

end

app/models/itinerary.rb
class Itinerary < ActiveRecord::Base
  belongs_to :user
  has_many :photos

  mount_uploader :logo, LogoUploader

  validates :title, presence: true, length: {maximum:50}

  scope :search, ->(keyword){ where('lower(title) LIKE ?', "%#{keyword.downcase}%") if keyword.present? }

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user

  mount_uploader :picture, PictureUploader
  # validates :poi_id, uniqueness: true, allow_nil: true
end

app/models/poi.rb
class Poi < ActiveRecord::Base
  # belongs_to :itinerary
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :photos, through: :itineraries
  has_many :itineraries

  validates :username, :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_user

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def require_logged_in
    return true if current_user

    redirect_to root_path
    return false
  end
end

app/controllers/itineraries_controller.rb
class ItinerariesController < ApplicationController
  before_action :set_itinerary, only: [:show, :edit, :update, :destroy]

  def index
    @itineraries = Itinerary.search(params[:keyword])
    if @itineraries.count == 0
      flash[:zero] = "Your search yielded no results!"
    end
  end

  def user_index
    require_logged_in
    @itineraries = current_user.itineraries.all
  end

  def show
    @itinerary = Itinerary.find(params[:id])
    # set show action to respond to AJAX request
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    require_logged_in
    @itinerary = current_user.itineraries.new
  end

  def edit
    require_logged_in
  end

  def edit_trail
    require_logged_in


  end

  def create
    # puts "i see this"
    @itinerary = current_user.itineraries.new(itinerary_params)

    respond_to do |format|
      if @itinerary.save
        format.html { redirect_to edit_itinerary_path(@itinerary), notice: 'Itinerary was successfully created.' }
        format.json { render :show, status: :created, location: @itinerary }
      else
        format.html { render :new }
        format.json { render json: @itinerary.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    require_logged_in
    respond_to do |format|
      if @itinerary.photos.count < 2
       redirect_to edit_itinerary_path(@itinerary), notice: 'Must have a minimum 2 photos!'
      else
        if @itinerary.update(itinerary_params)
          format.html { redirect_to @itinerary, notice: 'Itinerary was successfully updated.' }
          format.json { render :show, status: :ok, location: @itinerary }
        else
          format.html { render :edit }
          format.json { render json: @itinerary.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    require_logged_in
    @itinerary.destroy
    respond_to do |format|
      format.html { redirect_to itineraries_url, notice: 'Itinerary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary
      if current_user.present?
        @itinerary = Itinerary.find(params[:id])
      else
        @itinerary = Itinerary.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itinerary_params
      params.require(:itinerary).permit(:title, :description, :phone, :address, :city, :state, :zip, :twitter, :facebook, :instagram, :travel, :user_id)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  # before_action :require_logged_in
  #adjust for public pages

  # def index
  #   @photos = Photo.all
  # end
  #
  # def user_index
  #   @photos = current_user.photos.all
  # end

  def show

  end

  def index
    @itinerary = Itinerary.find(params[:itinerary_id])
    @photos = @itinerary.photos.all
  end

  # GET /photos/new
  # def new
  #   @itinerary = Itinerary.find(params[:itinerary_id])
  #   @photo = @itinerary.photos.new
  # end

  # GET /photos/1/edit
  # def edit
  # end

  # POST /photos
  # POST /photos.json
  def create
    @itinerary = Itinerary.find(params[:itinerary_id])
    @photo = @itinerary.photos.create(photo_params)

    redirect_to edit_itinerary_path(@itinerary)
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  # def update
  #   respond_to do |format|
  #     if @photo.update(photo_params)
  #       format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @photo }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @photo.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :latitude, :longitude, :itinerary_id, :picture, :poi_id, :user_id)
    end
    # future use extract data for premium users
    def set_gps_data
      @data = Exif::Data.new("#{Rails.root}/tmp/uploads/")
      @photo.longitude = -@data.gps_longitude
      @photo.latitude = @data.gps_latitude
      @photo.save
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:username]).
      try(:authenticate, params[:password])

      if @user
        session[:user_id] = @user.id

        # redirect_to 'itineraries#user_index'

        redirect_to root_path
        #this will change later it will indicate the
        #starting point for villagers after login
      else
        # render action: 'new'
        @user = User.new 
        render :new
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]


  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: "Created user"
    else
      render action:'new'
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_user
    #   @user = User.find(params[:id])
    # end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password_confirmation, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/itineraries/_form.html.erb
<div class="container uploaderbox2 text-center">
  <%= form_for(@itinerary) do |f| %>
  <% if @itinerary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@itinerary.errors.count, "error") %>
        prohibited this itinerary from being saved:</h2>

      <ul>
      <% @itinerary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">

    <%= f.radio_button(:travel, "WALKING", checked: true) %>
    <%= f.label(:travel, image_tag("walker.png", class:"travel-mode")) %>
    <%= f.radio_button(:travel, "BICYCLING") %>
    <%= f.label(:travel, image_tag("bicycle.png", class:"travel-mode2")) %>
    <%= f.radio_button(:travel, "DRIVING") %>
    <%= f.label(:travel, image_tag("car.png", class:"travel-mode3")) %>
  </div>

  <div class="actions">
    <%= f.submit "Done", id: "view-map" %>
  </div>
<% end %>
</div>

app/views/itineraries/edit.html.erb
<!-- Page headline -->
<div class="row headline">
  <h1>Create a trail </h1>
</div>
<div class="row instructions text-center">
  Add PicPins
</div>


<!-- upload photos to the new instance of Itinerary -->

<!--create itineary box -->
<div class="row">

  <div class="container uploaderbox text-center">
    <% count = @itinerary.photos.count %>
    <% if count < 10 %>
        <%= render '/photos/form' %>
      <% else %>
        <%= "Yo, to many pics, slow down!" %>
      <% end %>

    <h4 class="count"><%= count %> of 10</h4>
  </div>
</div>


<div class="row">
  <div class=" donebutton text-center">
    <%= link_to "DONE", itinerary_path, class: "btn btn-success", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Uploading..."} %>
  </div>
</div>

app/views/itineraries/edit_trail.html.erb
<h1>Edit Your trail</h1>

<%= form_for(@itinerary) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>

<% end %>

app/views/itineraries/index.html.erb
<style media="screen"></style>


<p id="notice"><%= notice %></p>

<!-- Page headline -->
<div class="row headline">
  <h1>Explore a trail</h1>
</div>
<div class="row tagline">
  <h4><strong>Look up!</strong></h4>
</div>
<!-- search bar -->
<div class="row">
  <div class="container">
    <div class="col-md-3">
      <form>
        <legend class="search">Search:</legend>
          <input id="search" type="text" class="form-control" value="<%= params[:keyword] %>" name="keyword" placeholder="enter your search">
      </form>
    </div>
  </div>
</div>
<!-- Map of trails near the user -->
<!-- flash alert if search yeilds no result -->
<div class="row text-center">
  <% flash.each do |key, value| %>
    <div class="lead alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<br>
<br>
<!-- Start gallery of images that represent trails -->
    <div class="container-fluid text-center trailleadpic">
      <% @itineraries.each do |itinerary| %>
        <% if itinerary.photos.first.present? %>
          <%= link_to image_tag(itinerary.photos.first.picture_url(:thumb), class: "leadpic"), itinerary, class:'picpin' %>
        <% end %>
      <% end %>
    </div>

<!-- End photo gallery of images that represent trails -->


    <%#@itineraries.each do |itinerary| %>
        <%# link_to image_tag(itinerary.photos.first.picture_url(:thumb)), itinerary %>
        <%# link_to 'Show', itinerary %>
        <%# link_to 'Edit', edit_itinerary_path(itinerary) %>
        <%# link_to 'Destroy', itinerary, method: :delete, data: { confirm: 'Are you sure?' } %>
      <%# end %>

app/views/itineraries/new.html.erb
  <div class="row headline">
    <h1>Create a trail </h1>
  </div>
  <div class="row instructions text-center">
    Name your trail
  </div>

<%= render 'form' %>

app/views/itineraries/show.html.erb
<div class="row headline">
  <h1><%= @itinerary.title %> by <%= link_to @itinerary.user.username, useritineraries_path(@itinerary.user_id)  %></h1>
</div>


<!--Social Networking Share buttons -->
<div class="row share">
  <share-button class="sharing"></share-button>
</div>


<!-- Map of itinerary -->
<div class="row map">
  <div id="map"></div>
</div>

<p id="trail-length"> | created <%= time_ago_in_words(@itinerary.created_at) %> ago </p>

<button type="button" class="btn btn-success" id="whereami">Where Am I?</button>

<br><br>

<!-- <button type="button" class="btn btn-success" id="whereami">Where Am I?</button>
<br><br> -->

<!--image thumbnails to open as model -->
<div class="container-fluid">
  <%= render @itinerary.photos %>


  <%= content_tag(:p, @itinerary.id, id: "trail" ) %>

  <%= content_tag(:p, @itinerary.travel, id: "travel") %>

</div>

<script>
          config = {
            networks: {
          email: {
            enabled: false
                },
          twitter: {
            description: "Explore a trail! Look up!"
          },
          facebook: {
            description: "Explore a trail! Look up!"
          },
          pintrist: {
            description: "Explore a trail! Look up!"
          },
            }
          };
          var shareButton = new ShareButton('.sharing', config)
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAIAW3z8RyJAAq5KFcziTTMSk9fh42xyRc&callback=initialize"></script>

app/views/itineraries/user_index.html.erb
<!-- User profile information  -->
  <div class="container top">
      <div class="row">
        <%= image_tag 'userlogo.png', class:'userlogo' %>
    </div>
  </div>
<!-- End User Profile information -->

<!-- User greeting Message  -->
<div class="container">
  <div class="row text-center">
    <div class="greeting">
      <%= "Hi, #{@current_user.username} !"%>
    </div>
    <%= link_to 'Ready to blaze a new trail?', new_itinerary_path, class: "btn btn-createtrail" %>
  </div>
</div>
<br>

<div class="container text-center">
  <div class="container-fluid">
      <% @itineraries.each do |itinerary| %>
          <% if itinerary.photos.first.present? %>
            <%= link_to image_tag(itinerary.photos.first.picture_url(:thumb)), itinerary %>
            <%= link_to image_tag("garbagecan.png"), itinerary, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%= image_tag("edit.png") %>
          <% end %>
      <% end %>
  </div>

  <%# @itineraries.each do |itinerary| %>
      <%# link_to image_tag(itinerary.photos.first.picture_url(:thumb)), itinerary %>
      <%# link_to 'Show', itinerary %>
      <%# link_to 'Edit', edittrail_path(itinerary) %>
      <%# link_to 'Destroy', itinerary, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%# end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div>
    <ul class="nav navbar-nav">
      <li><a href="#" onclick="history.back();"><i class="push fa fa-angle-double-left"></i></a></li>
      <li><a href="/itineraries#index"><i class="push fa fa-home"></i></a></li>
      <li><a href="/useritineraries"><i class="push fa fa-user"></i></a></li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PikTrail</title>

  <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/css/jasny-bootstrap.min.css">
  <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Rancho' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" type="text/css" href="/itineraries.scss">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <!-- Top bar with logo and City Scape-->
  <div class="container top">
    <div class="row loginstatus">
      <% if current_user.present?  %>
      <%= "Logged in as #{@current_user.username}" %>
      <%= link_to 'Log Out', log_out_path, method: :delete %>
    <% else %>
      <%= link_to 'LogIn/Signup', login_path %>
    <% end %>
  </div>
    <div class="row header">
      <%= image_tag 'cityscape.png', class:'cityscape' %><br>
      <%= image_tag 'piktrailogo.png', class:'logo' %>
  </div>
    <!--End top bar -->


  <!-- page content -->
  <%= yield %>
  <!--End page content -->

  <!--footer navigation begins-->



<%= render 'layouts/navbar' %>


<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/3.1.3/js/jasny-bootstrap.min.js"></script>
</div>
</body>
</html>

app/views/photos/_form.html.erb
<%= form_for([@itinerary, @itinerary.photos.new]) do |f| %>

<div class="container uploaderbox">

  <div class=" container text-center text-center ">
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <%= f.file_field :picture, id: "fileInput", class:"fileinput-new", data: { capture:"camera", accept:"image/*" } %>
      <%# f.file_field :picture, id: "fileInput", class:"fileinput-new" %>
      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 100px; height: 100px;">
      </div>
    </div>

    <%= f.hidden_field :latitude, :value => "", id: "latitude" %>
    <%= f.hidden_field :longitude, :value => "", id: "longitude" %>
</div>

<div>
    <%= f.button "ADD", class: "btn btn-success", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Uploading..."} %>
</div>
<% end %>

app/views/photos/_photo.html.erb
  <%= link_to image_tag(photo.picture_url(:thumb), id: photo.id, class: "thumbnails"), "#", id: "test#{photo.id}" %>
  <%= image_tag(photo.picture_url, id: "full#{photo.id}", class: "fullsize") %>
  <%# link_to image_tag(photo.picture_url(:thumb), id: photo.id, class: "thumbnails"), "#mymodal#{photo.id}", class:"mymodal-trigger" %>
  <%# link_to company_review(q.user_id), "#review-modal#{q.user_id}", class: "review-modal-trigger" %>
  <%# photo.latitude  %>
  <%# photo.longitude  %>
  <script>
    $(document).on('page:change', function(){
      $('#test<%= photo.id %>').on('click', function(){
        event.preventDefault();
        $('#full<%= photo.id %>').bPopup();
      });
    });
    </script>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Picture</th>
      <th>Poi</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.title %></td>
        <td><%= photo.latitude %></td>
        <td><%= photo.longitude %></td>
        <td><%= photo.picture %></td>
        <td><%= photo.user %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @photo.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @photo.longitude %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @photo.picture_url %>
</p>

<p>
  <strong>Poi:</strong>
  <%= @photo.poi %>
</p>

<p>
  <strong>User:</strong>
  <%= @photo.user %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>